name: build-xmrig

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.10'

      - name: Setup Dependencies
        run: |
          sudo apt update
          sudo apt install -y git make cmake gcc automake libtool autoconf libhwloc-dev libuv1-dev
        shell: bash

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake .. -DXMRIG_DEPS=../scripts/deps
          make -j$(nproc)
        shell: bash

      - name: Commit results to Github
        run: |
          git config --local user.email "lifeifei5320@gmail.com"
          git config --local user.name "momika233"
          git add .
          git commit -m "Nuclei Report" || echo "No changes to commit"
        shell: bash

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
